version: "3.8"
services:
  dev-odoo-santosa:
    image: custom-odoo:17.0
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile  # Specify the Dockerfile name
    container_name: dev-odoo-santosa
    shm_size: '2gb'
    volumes:
      - dev-odoo-santosa:/var/lib/odoo
      - ./santosa-project/odoo:/etc/odoo
      - ../customize/santosa-project:/mnt/addons-customize
    networks:
      - dev-santosa_project_network

volumes:
  dev-odoo-santosa:

networks:
  dev-santosa_project_network:
    name: dev-santosa_project_network
    driver: bridge